
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA IPADDR LBRACE NUMBER PIPE RBRACE RECORD_TYPE SLASH STATE TIMESTAMParchivo : linea archivoarchivo : linealinea : RECORD_TYPE PIPE TIMESTAMP PIPE STATE PIPE IPADDR PIPE NUMBER PIPE prefix PIPE as_pathprefix : IPADDR SLASH NUMBERas_path : as_element as_pathas_path : as_elementas_element : NUMBERas_element : as_setas_set : LBRACE as_set_list RBRACEas_set_list : NUMBER COMMA as_set_listas_set_list : NUMBER'
    
_lr_action_items = {'RECORD_TYPE':([0,2,19,20,21,22,24,27,],[3,3,-7,-3,-6,-8,-5,-9,]),'$end':([1,2,4,19,20,21,22,24,27,],[0,-2,-1,-7,-3,-6,-8,-5,-9,]),'PIPE':([3,6,8,10,12,15,18,],[5,7,9,11,13,17,-4,]),'TIMESTAMP':([5,],[6,]),'STATE':([7,],[8,]),'IPADDR':([9,13,],[10,14,]),'NUMBER':([11,16,17,19,21,22,23,27,28,],[12,18,19,-7,19,-8,26,-9,26,]),'SLASH':([14,],[16,]),'LBRACE':([17,19,21,22,27,],[23,-7,23,-8,-9,]),'RBRACE':([25,26,29,],[27,-11,-10,]),'COMMA':([26,],[28,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'archivo':([0,2,],[1,4,]),'linea':([0,2,],[2,2,]),'prefix':([13,],[15,]),'as_path':([17,21,],[20,24,]),'as_element':([17,21,],[21,21,]),'as_set':([17,21,],[22,22,]),'as_set_list':([23,28,],[25,29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> archivo","S'",1,None,None,None),
  ('archivo -> linea archivo','archivo',2,'p_archivo_multiple','parser.py',150),
  ('archivo -> linea','archivo',1,'p_archivo_single','parser.py',155),
  ('linea -> RECORD_TYPE PIPE TIMESTAMP PIPE STATE PIPE IPADDR PIPE NUMBER PIPE prefix PIPE as_path','linea',13,'p_linea','parser.py',160),
  ('prefix -> IPADDR SLASH NUMBER','prefix',3,'p_prefix','parser.py',173),
  ('as_path -> as_element as_path','as_path',2,'p_as_path_multiple','parser.py',178),
  ('as_path -> as_element','as_path',1,'p_as_path_single','parser.py',183),
  ('as_element -> NUMBER','as_element',1,'p_as_element_num','parser.py',188),
  ('as_element -> as_set','as_element',1,'p_as_element_set','parser.py',193),
  ('as_set -> LBRACE as_set_list RBRACE','as_set',3,'p_as_set','parser.py',198),
  ('as_set_list -> NUMBER COMMA as_set_list','as_set_list',3,'p_as_set_list_multiple','parser.py',203),
  ('as_set_list -> NUMBER','as_set_list',1,'p_as_set_list_single','parser.py',208),
]
